INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Go web编程','郑兆雄',79.00,30,90,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('SRE Google运维解密','Betsy Beyer',108.00,10,70,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('MySQL必知必会','Ben Forta',49.00,13,35,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('MySQL技术内幕','姜承尧',79.00,19,37,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Linux私房菜','鸟哥',118.00,23,79,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Go语言高并发与微服务实战','朱荣鑫',89.00,37,59,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Redis实战','Josiah L. Carlson',69.00,57,17,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Redis设计与实现','黄健宏',79.00,97,57,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('编译原理','Alfred V.Aho',89.00,37,97,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Linux/Unix系统编程手册','Michael Kerrisk',158.00,17,77,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Unix环境高级编程','W.Richard Stevens',128.00,29,89,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Unix网络编程','W.Richard Stevens',89.00,19,39,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Linux系统编程','Robert Love',79.00,53,35,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('操作系统设计与实现','Andrew S.Tanenbaum',69.00,51,17,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Linux程序设计','Neil Matthew',99.00,53,97,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('程序设计实践','Rob Pike',49.00,94,93,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('现代操作系统','Andrew S.Tanenbaum',69.00,51,17,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('深度探索C++对象模型','Stanley B.Lippman',69.00,51,17,'static/img/default.jpg');
INSERT INTO item (title, author ,price, sales , stock , img_path) VALUES('Inside the C++ Object Model','Stanley B.Lippman',69.00,51,17,'static/img/default.jpg');
