-- sidsa_service.iot_variant definition

CREATE TABLE `iot_variant` (
  `id` int NOT NULL AUTO_INCREMENT,
  `imei` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '设备IMEI',
  `port_id` int DEFAULT NULL COMMENT '接口ID',
  `device_id` int DEFAULT NULL COMMENT '设备ID',
  `var_id` int DEFAULT NULL COMMENT '变量ID',
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量名称',
  `name_en` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT 'i18n-en',
  `address_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量地址类型',
  `address_type2` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量地址类型2',
  `data_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量数据类型',
  `read_write` int DEFAULT NULL COMMENT '读写类型(0:读，1：写)',
  `note` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '变量描述',
  `unit` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量单位',
  `offset` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量偏移地址',
  `offset2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '变量偏移地址2',
  `is_linear` int DEFAULT NULL COMMENT '是否线性转换',
  `in_min` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '输入最小值',
  `in_max` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '输入最大值',
  `out_min` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '输出最小值',
  `var_group` tinyint DEFAULT '0' COMMENT '0.其它 1.破碎机 2.混合器 3.固体泵',
  `out_max` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '输出最大值',
  `sort` int NOT NULL DEFAULT '0' COMMENT '自定义排序字段',
  `linear_data_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '输出类型',
  `latest_report_time` int DEFAULT NULL COMMENT 'latest_report_time',
  `deleted_at` datetime(3) DEFAULT NULL,
  `is_show` tinyint(1) NOT NULL DEFAULT '1' COMMENT '0不显示 1显示',
  `var_type` tinyint DEFAULT '1' COMMENT '1.gateway var 2.customize var ',
  `expression` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '',
  `expression_args` json DEFAULT NULL,
  `custom_group` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '自定义分组',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=94595 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;