-- shuwen.store_order definition

CREATE TABLE `store_order` (
  `order_id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `main_id` int(11) unsigned DEFAULT '0' COMMENT '拆单前 id',
  `group_order_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '订单组 id',
  `order_sn` varchar(32) NOT NULL COMMENT '订单号',
  `uid` int(11) unsigned NOT NULL COMMENT '用户id',
  `spread_uid` int(11) unsigned DEFAULT '0' COMMENT '推荐人id',
  `top_uid` int(11) unsigned DEFAULT '0' COMMENT '二级推荐人 id',
  `real_name` varchar(32) NOT NULL COMMENT '用户姓名',
  `user_phone` varchar(18) NOT NULL COMMENT '用户电话',
  `user_address` varchar(128) NOT NULL COMMENT '详细地址',
  `cart_id` varchar(256) NOT NULL COMMENT '购物车id',
  `total_num` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '订单商品总数',
  `total_price` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '订单总价',
  `total_postage` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '邮费',
  `pay_price` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '实际支付金额',
  `pay_postage` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '支付邮费',
  `is_selfbuy` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否为自购',
  `extension_one` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '一级佣金',
  `extension_two` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '二级佣金',
  `commission_rate` decimal(7,4) unsigned NOT NULL DEFAULT '0.0000' COMMENT '平台手续费',
  `integral` int(8) unsigned DEFAULT '0' COMMENT '使用积分数量',
  `integral_price` decimal(8,2) unsigned DEFAULT '0.00' COMMENT '积分抵扣金额',
  `give_integral` int(8) unsigned DEFAULT '0' COMMENT '赠送积分',
  `coupon_id` varchar(128) NOT NULL DEFAULT '' COMMENT '优惠券id',
  `coupon_price` decimal(8,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '优惠券金额',
  `platform_coupon_price` decimal(8,2) unsigned DEFAULT '0.00' COMMENT '平台优惠券金额',
  `svip_discount` decimal(8,2) unsigned DEFAULT '0.00' COMMENT 'svip优惠金额',
  `order_type` tinyint(1) unsigned DEFAULT '0' COMMENT '0普通1自提',
  `paid` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '支付状态',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `pay_type` tinyint(1) NOT NULL COMMENT '支付方式 0余额 1微信 2小程序 3 h5  4支付宝 5 支付宝扫码 6 微信扫码',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '订单状态（0：待发货；1：待收货；2：待评价；3：已完成； 9: 拼团中 10:  待付尾款 11:尾款超时未付 -1：已退款）',
  `delivery_type` varchar(32) DEFAULT NULL COMMENT '发货类型(1:发货 2: 送货 3: 虚拟,4电子面单，5同城 6 卡密自动发货)',
  `is_virtual` tinyint(1) unsigned DEFAULT '0' COMMENT '0:实物订单 1:虚拟订单',
  `delivery_name` varchar(50) DEFAULT NULL COMMENT '快递名称/送货人姓名',
  `delivery_id` varchar(255) DEFAULT NULL COMMENT '快递单号/手机号',
  `mark` varchar(512) NOT NULL COMMENT '备注',
  `remark` varchar(512) DEFAULT NULL COMMENT '管理员备注',
  `admin_mark` varchar(512) DEFAULT NULL COMMENT '总后台备注',
  `verify_code` char(16) DEFAULT NULL COMMENT '核销码',
  `verify_time` timestamp NULL DEFAULT NULL COMMENT '核销时间/收货时间',
  `verify_service_id` int(10) unsigned DEFAULT NULL COMMENT '核销客服 id',
  `transaction_id` varchar(60) DEFAULT NULL COMMENT '微信支付订单号(分账时有效)',
  `activity_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '1:秒杀 2:预售 3:助力 10:套餐',
  `order_extend` varchar(1024) DEFAULT NULL COMMENT '自定义表单数据',
  `mer_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '商户ID',
  `reconciliation_id` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '对账id',
  `cost` decimal(8,2) unsigned NOT NULL COMMENT '成本价',
  `is_del` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  `is_system_del` tinyint(1) DEFAULT '0' COMMENT '后台是否删除',
  `verify_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '核销订单状态0 默认 1 部分核销 2 全部核销',
  `refund_switch` tinyint(1) unsigned DEFAULT '1' COMMENT '是否支持退款',
  `kuaidi_label` varchar(255) DEFAULT NULL COMMENT '快递单号图片',
  PRIMARY KEY (`order_id`) USING BTREE,
  UNIQUE KEY `order_id_2` (`order_id`) USING BTREE,
  KEY `uid` (`uid`) USING BTREE,
  KEY `mer_id` (`mer_id`) USING BTREE,
  KEY `verify_code` (`verify_code`),
  KEY `main_id` (`main_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8 COMMENT='订单表';