-- sidsa_service.iot_box_desc definition

CREATE TABLE `iot_box_desc` (
  `id` int NOT NULL AUTO_INCREMENT,
  `box_id` int NOT NULL COMMENT '对应 iot_box 的id',
  `imei` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"机械序列号"',
  `city` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `maintenance_expiration_date` datetime DEFAULT NULL COMMENT '维保到期时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` datetime(3) DEFAULT NULL,
  `shun_num` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"顺号"',
  `project_number` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"项目号"',
  `presale_number` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"售前号"',
  `customer` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"客户信息"',
  `model` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"机型"',
  `quantity` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"数量"',
  `actual_imei` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"实际发货机械序列号"',
  `machine_manager` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"机械负责人"',
  `hydraulics_manager` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"液压负责人"',
  `electrical_manager` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"电气负责人"',
  `sales_manager` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"销售负责人"',
  `project_start_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"项目启动会日期 "',
  `actual_project_start_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"项目实际启动日期"',
  `contract_signing_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"合同签订日期"',
  `delivery_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"交货日期"',
  `actual_delivery_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"实际发货日期 "',
  `actual_commissioning_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"实际调试日期"',
  `delivery_warranty` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"交货质保期"',
  `commissioning_warranty_period` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"调试质保期"',
  `warranty_expiration_date` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"质保到期日"',
  `rd_manager` varchar(256) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '"研发负责人"',
  `online_status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 在线 0 离线',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=941 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='项目描述信息';